<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.242">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<link rel="stylesheet" href="styles.css" type="text/css">

<title>decision-tree</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>

<script src="nav.js"></script>
<script src="Decision tree_files/libs/clipboard/clipboard.min.js"></script>
<script src="Decision tree_files/libs/quarto-html/quarto.js"></script>
<script src="Decision tree_files/libs/quarto-html/popper.min.js"></script>
<script src="Decision tree_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Decision tree_files/libs/quarto-html/anchor.min.js"></script>
<link href="Decision tree_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Decision tree_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Decision tree_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Decision tree_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Decision tree_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#introduction-to-decision-tree" id="toc-introduction-to-decision-tree" class="nav-link active" data-scroll-target="#introduction-to-decision-tree">Introduction to Decision Tree</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">EDA</a></li>
  <li><a href="#class-distribution" id="toc-class-distribution" class="nav-link" data-scroll-target="#class-distribution">Class Distribution</a></li>
  <li><a href="#baseline-model-for-comparison" id="toc-baseline-model-for-comparison" class="nav-link" data-scroll-target="#baseline-model-for-comparison">Baseline model for comparison</a></li>
  <li><a href="#wrapper-method-feature-selection" id="toc-wrapper-method-feature-selection" class="nav-link" data-scroll-target="#wrapper-method-feature-selection">Wrapper Method Feature selection</a></li>
  <li><a href="#data-split" id="toc-data-split" class="nav-link" data-scroll-target="#data-split">Data Split</a></li>
  <li><a href="#training-model" id="toc-training-model" class="nav-link" data-scroll-target="#training-model">Training Model</a></li>
  <li><a href="#hyperparameter-optimization-model-tuning" id="toc-hyperparameter-optimization-model-tuning" class="nav-link" data-scroll-target="#hyperparameter-optimization-model-tuning">Hyperparameter Optimization (Model tuning)</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">



<section id="introduction-to-decision-tree" class="level1">
<h1>Introduction to Decision Tree</h1>
<p>A decision tree is a graph that resembles a tree, with nodes denoting the locations where we choose an attribute(feature) and pose a question, edges denoting the responses to the question, and leaves denoting the actual output or class label.</p>
<p>In this section, we will use the decision tree method to do the binary classification which also called binary decision tree. So, each note in the binary decision tree will split the data into two groups(classes) of data until we are left with pure leaf node which means all of its data belongs to a single class.</p>
<p>The data we will apply decision tree on can be found here https://digital.csic.es/handle/10261/226973?mode=full and this is a marijuana related data. I will use the data from this research paper to train the Decision Tree. The dataset is uploaded in an Excel format, containing 4 sheets: Table 1, Table 2, Publications and Abbreviations and Explanations . The main sheet is Table 1, which contains 2332 rows and 38 columns and Table 1 is the one we are going to use. We will use the column Plant parts used which consists of 11 sub columns and system category column which represents what parts of the body will the marijuana be used for to train the decision tree model. In the end, we can use the model to predict what part of body the marijuana will be used based on the part of marijuana.</p>
</section>
<section id="data-cleaning" class="level1">
<h1>Data Cleaning</h1>
<p>In this part, we will remove or fix incorrect, corrupted, incorrectly formatted, duplicate, or incomplete data within a dataset.</p>
<div class="cell" data-execution_count="57">
<div class="cell-output cell-output-display" data-execution_count="57">
<pre><code>array(['Unclassified', 'Digestive system and nutritional disorders',
       'Infections and infestations', ...,
       'Nervous system and mental disorders', 'Pain and inflammations',
       'Musculoskeletal system disorders and traumas'], dtype=object)</code></pre>
</div>
</div>
<p>The table above is the data. from column “Ln” to “O” represents the parts of marijuana. Those columns only have binary representations (0 or 1). <br> “Ln” represents Inflorescence <br> “L” represents Leaf <br> “Wp” represents Whole plant <br> “Se*” represents Seed <br> “Ap” represents Aerial part <br> “St” represents Stem <br> “Bk” represents Bark <br> “Rt” represents Root <br> “TwB” represents Twig and branch <br> “Sh” represents Shoot <br> “O” represents Other plant parts <br></p>
<p>The System category column has 17 different values and they are “circulatory system and blood disorders”, “digestive system and nutritional disorders”,” endocrine system and metabolic disorders”, “genitourinary system disorders”, “immune system disorders and neoplasia”, “infections and infestations”, “musculoskeletal system disorders and traumas”, “nervous system and mental disorders”,” pain and inflammations”,” poisoning, pregnancy”, “birth and puerperal disorders”, “respiratory system disorders”, “sensory system disorders”, “skin and subcutaneous tissue disorders”, “tonic and restorative and unclassified”. <br></p>
<p>By removing the the row without values on System category column and the row with no value on all Plant parts columns. or negative values on Plant parts columns</p>
<div class="cell" data-execution_count="58">
<div class="cell-output cell-output-display" data-execution_count="58">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>In</th>
      <th>L</th>
      <th>Wp</th>
      <th>Se*</th>
      <th>Ap</th>
      <th>St</th>
      <th>Bk</th>
      <th>Rt</th>
      <th>TwB</th>
      <th>Sh</th>
      <th>O</th>
      <th>System category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Digestive system and nutritional disorders</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Infections and infestations</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Infections and infestations</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Pregnancy, birth and puerperal disorders</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Veterinary use</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2325</th>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Nervous system and mental disorders</td>
    </tr>
    <tr>
      <th>2326</th>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Nervous system and mental disorders</td>
    </tr>
    <tr>
      <th>2327</th>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Nervous system and mental disorders</td>
    </tr>
    <tr>
      <th>2328</th>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Pain and inflammations</td>
    </tr>
    <tr>
      <th>2329</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>Musculoskeletal system disorders and traumas</td>
    </tr>
  </tbody>
</table>
<p>1584 rows × 12 columns</p>
</div>
</div>
</div>
</section>
<section id="eda" class="level1">
<h1>EDA</h1>
<p>exploring data</p>
<div class="cell" data-execution_count="85">
<div class="cell-output cell-output-stdout">
<pre><code>(12, 12)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Decision%20tree_files/figure-html/cell-6-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Correlation Heat map</p>
<div class="cell" data-execution_count="88">
<div class="cell-output cell-output-display" data-execution_count="88">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Se*</th>
      <th>L</th>
      <th>Bk</th>
      <th>Rt</th>
      <th>TwB</th>
      <th>In</th>
      <th>Ap</th>
      <th>O</th>
      <th>St</th>
      <th>System category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>2</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2325</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>5</td>
    </tr>
    <tr>
      <th>2326</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>5</td>
    </tr>
    <tr>
      <th>2327</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>5</td>
    </tr>
    <tr>
      <th>2328</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
    </tr>
    <tr>
      <th>2329</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>10</td>
    </tr>
  </tbody>
</table>
<p>1584 rows × 10 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="91">
<div class="cell-output cell-output-stdout">
<pre><code>(1584, 12)</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Decision%20tree_files/figure-html/cell-8-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>After removing all blank rows, we only have 1584 rows left</p>
</section>
<section id="class-distribution" class="level1">
<h1>Class Distribution</h1>
<p>In this part, I will show the distribution of the class labels in the dataset</p>
<div class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>0     262
5     251
1     172
4     145
3     135
7     116
15    114
10     64
6      62
12     49
8      43
11     38
9      37
13     33
14     29
16     25
2       9
Name: System category, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="63">
<div class="cell-output cell-output-display">
<p><img src="Decision%20tree_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16}</code></pre>
</div>
</div>
<p>I rename each class from 0-16 and the text under the graph is the numerical label and its corresponding text label. The plot shows that data class is unbalanced. The label “0” has most count among all the classes.</p>
</section>
<section id="baseline-model-for-comparison" class="level1">
<h1>Baseline model for comparison</h1>
<p>In this part. We will define a classification method called “random classifier” that randomly chooses the label between the classes and we will use the random selection as our predicted labels. So, the random classifier will give us the worse case for the given classification problem and we can use the result from the random classifier to compare the result from DT model we are going to use later.</p>
<p>Since we just do the random selection so how well the random classifier does depends on the number of classes, and the load balance between classes.</p>
<div class="cell" data-execution_count="67">
<div class="cell-output cell-output-stdout">
<pre><code>-----RANDOM CLASSIFIER-----
count of prediction: dict_values([263, 105, 38, 257, 150, 159, 66, 43, 117, 146, 35, 27, 32, 61, 54, 21, 10])
probability of prediction: [0.16603535 0.06628788 0.0239899  0.16224747 0.09469697 0.10037879
 0.04166667 0.02714646 0.07386364 0.09217172 0.02209596 0.01704545
 0.02020202 0.0385101  0.03409091 0.01325758 0.00631313]
accuracy 0.09027777777777778
percision, recall, fscore, (array([0.14068441, 0.12578616, 0.        , 0.06849315, 0.09333333,
       0.14007782, 0.06060606, 0.07619048, 0.02631579, 0.        ,
       0.03278689, 0.        , 0.01851852, 0.03703704, 0.02857143,
       0.06837607, 0.        ]), array([0.14122137, 0.11627907, 0.        , 0.07407407, 0.09655172,
       0.14342629, 0.06451613, 0.06896552, 0.02325581, 0.        ,
       0.03125   , 0.        , 0.02040816, 0.03030303, 0.03448276,
       0.07017544, 0.        ]), array([0.14095238, 0.12084592, 0.        , 0.07117438, 0.09491525,
       0.14173228, 0.0625    , 0.07239819, 0.02469136, 0.        ,
       0.032     , 0.        , 0.01941748, 0.03333333, 0.03125   ,
       0.06926407, 0.        ]), array([262, 172,   9, 135, 145, 251,  62, 116,  43,  37,  64,  38,  49,
        33,  29, 114,  25], dtype=int64))</code></pre>
</div>
</div>
</section>
<section id="wrapper-method-feature-selection" class="level1">
<h1>Wrapper Method Feature selection</h1>
<p>In this method, a subset of features are selected and train a model using them. This an iterative method in which we start with having no feature in the model. In each iteration, we keep adding the feature which best improves our model till an addition of a new variable does not improve the performance of the model.</p>
<div class="cell" data-execution_count="69">
<div class="cell-output cell-output-stderr">
<pre><code>d:\python\envs\ANLY580\lib\site-packages\sklearn\feature_selection\_sequential.py:188: FutureWarning: Leaving `n_features_to_select` to None is deprecated in 1.0 and will become 'auto' in 1.3. To keep the same behaviour as with None (i.e. select half of the features) and avoid this warning, you should manually set `n_features_to_select='auto'` and set tol=None when creating an instance.
  warnings.warn(</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="69">
<style>#sk-container-id-2 {color: black;background-color: white;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>SequentialFeatureSelector(estimator=DecisionTreeClassifier())</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-4" type="checkbox"><label for="sk-estimator-id-4" class="sk-toggleable__label sk-toggleable__label-arrow">SequentialFeatureSelector</label><div class="sk-toggleable__content"><pre>SequentialFeatureSelector(estimator=DecisionTreeClassifier())</pre></div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-5" type="checkbox"><label for="sk-estimator-id-5" class="sk-toggleable__label sk-toggleable__label-arrow">estimator: DecisionTreeClassifier</label><div class="sk-toggleable__content"><pre>DecisionTreeClassifier()</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-6" type="checkbox"><label for="sk-estimator-id-6" class="sk-toggleable__label sk-toggleable__label-arrow">DecisionTreeClassifier</label><div class="sk-toggleable__content"><pre>DecisionTreeClassifier()</pre></div></div></div></div></div></div></div></div></div></div>
</div>
</div>
<div class="cell" data-execution_count="70">
<div class="cell-output cell-output-stdout">
<pre><code>number of features 5
shape of X (1584, 5)</code></pre>
</div>
</div>
</section>
<section id="data-split" class="level1">
<h1>Data Split</h1>
<p>In this part, we split data into four parts which are x_train,y_train,x_test,y_test with ratio = 0.2</p>
<div class="cell" data-execution_count="72">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'numpy.ndarray'&gt; (1267, 5)
&lt;class 'pandas.core.series.Series'&gt; (1267,)
&lt;class 'numpy.ndarray'&gt; (317, 5)
&lt;class 'pandas.core.series.Series'&gt; (317,)</code></pre>
</div>
</div>
</section>
<section id="training-model" class="level1">
<h1>Training Model</h1>
<div class="cell" data-execution_count="75">
<div class="cell-output cell-output-display" data-execution_count="75">
<pre><code>Text(0.5, 1.0, 'confusion matrix for test data')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Decision%20tree_files/figure-html/cell-20-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="76">
<div class="cell-output cell-output-stderr">
<pre><code>d:\python\envs\ANLY580\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\python\envs\ANLY580\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\python\envs\ANLY580\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="76">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>precision</th>
      <th>recall</th>
      <th>f1-score</th>
      <th>support</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.176252</td>
      <td>0.917874</td>
      <td>0.295720</td>
      <td>207.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>134.000000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>7.000000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>104.000000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>116.000000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.264865</td>
      <td>0.240196</td>
      <td>0.251928</td>
      <td>204.000000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>52.000000</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.333333</td>
      <td>0.010638</td>
      <td>0.020619</td>
      <td>94.000000</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>33.000000</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>28.000000</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>52.000000</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1.000000</td>
      <td>0.038462</td>
      <td>0.074074</td>
      <td>26.000000</td>
    </tr>
    <tr>
      <th>12</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>39.000000</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>29.000000</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>22.000000</td>
    </tr>
    <tr>
      <th>15</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>96.000000</td>
    </tr>
    <tr>
      <th>16</th>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>24.000000</td>
    </tr>
    <tr>
      <th>accuracy</th>
      <td>0.190213</td>
      <td>0.190213</td>
      <td>0.190213</td>
      <td>0.190213</td>
    </tr>
    <tr>
      <th>macro avg</th>
      <td>0.104379</td>
      <td>0.071010</td>
      <td>0.037785</td>
      <td>1267.000000</td>
    </tr>
    <tr>
      <th>weighted avg</th>
      <td>0.116693</td>
      <td>0.190213</td>
      <td>0.091927</td>
      <td>1267.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>The result looks so bad. the highest precision is only 0.33 and half of the classes have 0 precision which means they have no correct prediction on their classes. the accuracy of the class is <span class="math inline">\(\frac{45+7} {317}\)</span> = 0.164 which is higher than the one we got from random classifier.</p>
<p>Now, let’s see if we can prove the results a little bit by model tuning</p>
</section>
<section id="hyperparameter-optimization-model-tuning" class="level1">
<h1>Hyperparameter Optimization (Model tuning)</h1>
<p>For the decision tree model, we have a hyperparameter called max depth which controls the number of layers in the decision tree. The following step is going to change the the max depth and training the model with different max depth, then record the accuracy and recall for each models. Finally, we will choose one with the best performance as our final model.</p>
<div class="cell" data-execution_count="25">
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\l7989\AppData\Local\Temp\ipykernel_20528\1786278836.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  for n, y in enumerate(np.array(train_results)[:,2]):
C:\Users\l7989\AppData\Local\Temp\ipykernel_20528\1786278836.py:12: MatplotlibDeprecationWarning: Auto-removal of overlapping axes is deprecated since 3.6 and will be removed two minor releases later; explicitly call ax.remove() as needed.
  ax = plt.subplot(5, 4, n + 1)
C:\Users\l7989\AppData\Local\Temp\ipykernel_20528\1786278836.py:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ax.plot(np.array(train_results)[:,0],[r[n] for r in np.array(train_results)[:,2]],'-o')
C:\Users\l7989\AppData\Local\Temp\ipykernel_20528\1786278836.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ax.plot(np.array(test_results)[:,0],[r[n] for r in np.array(test_results)[:,2]],'-o',c="red")</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Decision%20tree_files/figure-html/cell-23-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>From above graph, we can see there is no improvement for the model performance.</p>
<div class="cell" data-execution_count="82">
<div class="cell-output cell-output-display">
<p><img src="Decision%20tree_files/figure-html/cell-24-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Descision Tree with number of layers = 3</p>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<p>The result is not good. Half of the Classes only have 0 precision and the accuracy is pretty low. So, I list some points that may cause accuracy and performance of the model.</p>
<li>
Small sample size
</li>
<p>In this dataset, we only have 1584 samples, however, we have 17 classes in the data. So, the average sample size of each class should be around 90 samples/class. Due to the unbalanced distribution of samples/classes (see fig.&nbsp;distribution of class), we can see the label “0” has 250 + samples and label “2” only have 9 samples. So, small number of observations in test data may be too few to give meaningful performance estimate, and/or number of observations in cross-validation data may be too few to guide parameter search optimally.</p>
<li>
Low correlation between features and classes
</li>
<p>From pervious heat map, we can see all There is no high correlation between all features and classes. So, there is no point to use these features to predict the classes.</p>
<p>Also, I come up with two ways to solve the issues.</p>
<li>
Find more data
</li>
<p>Trying to find more data with large number of samples size. Also, Find more feature so we can do feature selection to selection different features that have high correlation with the label classes.</p>
<li>
Switch to different models
</li>
<p>From my research, it shows that the decision tree algorithm is effective for balanced classification, although it does not perform well on imbalanced datasets. The split points of the tree are chosen to best separate examples into two groups with minimum mixing (by Jason Brownlee on January 29, 2020 in Imbalanced Classification). So, the alternative way is to find a model that can handle imbalanced classification problem.</p>
</section>
<section id="reference" class="level1">
<h1>Reference</h1>
<p>Code: https://github.com/anly501/anly-501-project-yanyanli0/tree/main/codes in 06-decision tree file</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>